#!/bin/bash

# first, install this:
# brew install https://raw.github.com/Homebrew/homebrew-dupes/master/apple-gcc42.rb

export CC=/usr/local/bin/gcc-4.2&&export CXX=/usr/local/bin/g++-4.2
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home
export PATH=$JAVA_HOME/bin:$PATH
. setenv
make -j4 WITH_DEXPREOPT=false || exit 1

exit 0
